FROM python:3.8.6

# set working directory in container
WORKDIR /usr/src/app

# Copy and install packages
COPY requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

# Changing to non-root user
RUN useradd -m appUser
USER appUser

# Copy app folder to app folder in container
COPY /src /usr/src/app/

# Run locally on port 8050:
CMD gunicorn --bind 0.0.0.0:$PORT app:server